/**
 * Seed da tabela tournaments com dados oficiais 2026.
 * Run: npx tsx scripts/seed-tournaments.ts
 *
 * Dados verificados via Wikipedia API. Em produção será substituido por
 * cron Python que faz scrape automático de https://en.wikipedia.org/wiki/2026_ATP_Tour
 */
import { config } from 'dotenv';
import { createClient } from '@supabase/supabase-js';

config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  { auth: { persistSession: false } }
);

// Helper: get player id by slug
async function getPlayerId(slug: string): Promise<number | null> {
  const { data } = await supabase
    .from('players')
    .select('id')
    .eq('slug', slug)
    .single();
  return data?.id ?? null;
}

const tournaments = [
  // FINISHED — 2026
  {
    slug: 'australian-open-2026',
    name: 'Australian Open',
    full_name: 'Australian Open 2026',
    year: 2026,
    tour: 'both',
    category: 'slam',
    surface: 'hard',
    surface_label: 'Hard · outdoor',
    location: 'Melbourne Park · 🇦🇺',
    country: 'AUS',
    flag: '🇦🇺',
    start_date: '2026-01-12',
    end_date: '2026-02-01',
    prize_money: 'A$96.5M',
    draw_size: '128S · 64D · 16X',
    status: 'finished',
    atp_winner: 'carlos-alcaraz',
    atp_finalist: 'novak-djokovic',
    atp_score: '2-6, 6-2, 6-3, 7-5',
    wta_winner: null, // Rybakina não está nos players seeded
    wta_finalist: 'aryna-sabalenka',
    wta_score: '6-4, 4-6, 6-4',
    story: 'Final histórica: Alcaraz conquistou o 1º Australian Open da carreira ao vencer Djokovic em 4 sets, completando o Career Grand Slam. Rybakina venceu o 2º Slam batendo Sabalenka numa final dramática de 3 sets.',
    wiki_slug: '2026_Australian_Open',
  },
  {
    slug: 'rotterdam-open-2026',
    name: 'ABN AMRO Open',
    full_name: 'ABN AMRO Open 2026',
    year: 2026,
    tour: 'atp',
    category: '500',
    surface: 'indoor',
    surface_label: 'Indoor · hard',
    location: 'Rotterdam Ahoy · 🇳🇱',
    country: 'NED',
    flag: '🇳🇱',
    start_date: '2026-02-09',
    end_date: '2026-02-15',
    prize_money: '€2.5M',
    draw_size: '32S · 16D',
    status: 'finished',
    atp_winner: 'alex-de-minaur',
    atp_finalist: 'felix-auger-aliassime',
    atp_score: '6-3, 6-2',
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'De Minaur conquistou um dos maiores títulos da carreira ao vencer Auger-Aliassime numa final dominante de 2 sets. O australiano consolida o regresso ao top 5 ATP em piso indoor.',
    wiki_slug: '2026_ABN_AMRO_Open',
  },
  {
    slug: 'indian-wells-2026',
    name: 'BNP Paribas Open',
    full_name: 'BNP Paribas Open 2026 (Indian Wells)',
    year: 2026,
    tour: 'both',
    category: '1000',
    surface: 'hard',
    surface_label: 'Hard · outdoor',
    location: 'Indian Wells Tennis Garden · 🇺🇸',
    country: 'USA',
    flag: '🏜️',
    start_date: '2026-03-04',
    end_date: '2026-03-15',
    prize_money: '$9,415,725',
    draw_size: '96S · 32D · 16X',
    status: 'finished',
    atp_winner: 'jannik-sinner',
    atp_finalist: 'carlos-alcaraz',
    atp_score: '7-6(8-6), 7-6(7-4)',
    wta_winner: 'elena-rybakina',
    wta_finalist: 'iga-swiatek',
    wta_score: '3-6, 6-3, 7-6(8-6)',
    story: 'Final ATP épica decidida em 2 tiebreaks após mais de 3h de jogo — o jogo mais longo do ano em hard. Rybakina vingou-se de Świątek num 3º set tiebreak igualmente dramático, conquistando o 1º título WTA 1000 fora da grama.',
    wiki_slug: '2026_BNP_Paribas_Open',
  },
  {
    slug: 'miami-open-2026',
    name: 'Miami Open',
    full_name: 'Miami Open 2026',
    year: 2026,
    tour: 'both',
    category: '1000',
    surface: 'hard',
    surface_label: 'Hard · outdoor',
    location: 'Hard Rock Stadium, Miami · 🇺🇸',
    country: 'USA',
    flag: '🇺🇸',
    start_date: '2026-03-17',
    end_date: '2026-03-29',
    prize_money: '$9,415,725',
    draw_size: '96S · 48Q · 32D',
    status: 'finished',
    atp_winner: 'jannik-sinner',
    atp_finalist: null, // Lehečka não está nos players (vou criar nome só)
    atp_score: '6-4, 6-4',
    wta_winner: 'coco-gauff',
    wta_finalist: 'iga-swiatek',
    wta_score: '6-2, 4-6, 6-3',
    story: 'Sinner somou o 2º título Masters consecutivo em Miami, com uma final eficiente de 2 sets contra a sensação tcheca Lehečka, que tinha eliminado Alcaraz na meia-final. Gauff conquistou Miami em casa, derrotando Świątek em 3 sets.',
    wiki_slug: '2026_Miami_Open',
  },
  {
    slug: 'monte-carlo-2026',
    name: 'ATP Monte Carlo',
    full_name: 'Rolex Monte-Carlo Masters 2026',
    year: 2026,
    tour: 'atp',
    category: '1000',
    surface: 'clay',
    surface_label: 'Saibro · outdoor',
    location: 'Monte Carlo Country Club · 🇲🇨',
    country: 'MCO',
    flag: '🇲🇨',
    start_date: '2026-04-05',
    end_date: '2026-04-12',
    prize_money: '€6,130,965',
    draw_size: '56S · 28D',
    status: 'finished',
    atp_winner: 'jannik-sinner',
    atp_finalist: 'carlos-alcaraz',
    atp_score: '7-6(5), 6-3',
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'Final histórica entre os dois melhores: Sinner conseguiu a 1ª vitória da carreira em Monte Carlo, batendo Alcaraz em 2 sets numa decisão de tiebreak no 1º. O resultado contraria 5 anos de domínio espanhol no torneio.',
    wiki_slug: '2026_Monte-Carlo_Masters',
  },
  {
    slug: 'barcelona-open-2026',
    name: 'ATP Barcelona',
    full_name: 'Barcelona Open Banc Sabadell 2026',
    year: 2026,
    tour: 'atp',
    category: '500',
    surface: 'clay',
    surface_label: 'Saibro · outdoor',
    location: 'Real Club de Tenis Barcelona · 🇪🇸',
    country: 'ESP',
    flag: '🇪🇸',
    start_date: '2026-04-13',
    end_date: '2026-04-19',
    prize_money: '€2.9M',
    draw_size: '48S · 16D',
    status: 'finished',
    atp_winner: 'arthur-fils',
    atp_finalist: 'lorenzo-musetti',
    atp_score: '6-2, 7-6(7-2)',
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'Surpresa do circuito em saibro: o jovem francês Arthur Fils conquistou o 1º ATP 500 da carreira, batendo Musetti com autoridade após este ter eliminado o defensor Alcaraz nos quartos.',
    wiki_slug: '2026_Barcelona_Open_Banc_Sabadell',
  },
  {
    slug: 'mutua-madrid-open-2026',
    name: 'Mutua Madrid Open',
    full_name: 'Mutua Madrid Open 2026',
    year: 2026,
    tour: 'both',
    category: '1000',
    surface: 'clay',
    surface_label: 'Saibro · outdoor',
    location: 'Caja Mágica, Madrid · 🇪🇸',
    country: 'ESP',
    flag: '🇪🇸',
    start_date: '2026-04-21',
    end_date: '2026-05-03',
    prize_money: '€8,235,540',
    draw_size: '96S · 32D',
    status: 'finished',
    atp_winner: 'jannik-sinner',
    atp_finalist: 'alexander-zverev',
    atp_score: '6-1, 6-2',
    wta_winner: 'marta-kostyuk',
    wta_finalist: 'coco-gauff',
    wta_score: '6-3, 7-5',
    story: 'Sinner conquistou Madrid pela primeira vez com uma final dominante de 6-1, 6-2 contra Zverev — uma das exibições mais perfeitas do ano em saibro. Marta Kostyuk consagrou-se como nova surpresa do circuito ao bater Coco Gauff em 2 sets.',
    wiki_slug: '2026_Mutua_Madrid_Open',
  },
  // LIVE
  {
    slug: 'rome-masters-2026',
    name: 'Internazionali BNL d\'Italia',
    full_name: 'Internazionali BNL d\'Italia 2026',
    year: 2026,
    tour: 'both',
    category: '1000',
    surface: 'clay',
    surface_label: 'Saibro · outdoor',
    location: 'Foro Italico, Roma · 🇮🇹',
    country: 'ITA',
    flag: '🔴',
    start_date: '2026-05-07',
    end_date: '2026-05-18',
    prize_money: '€8.45M',
    draw_size: '96S · 32D',
    status: 'live',
    atp_winner: null, atp_finalist: null, atp_score: null,
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'Em curso. O modelo prevê: Alcaraz 28% · Sinner 22% · ⭐ Musetti +91% edge na quota mercado.',
    wiki_slug: '2026_Italian_Open',
  },
  // UPCOMING
  {
    slug: 'roland-garros-2026',
    name: 'Roland Garros',
    full_name: 'French Open 2026',
    year: 2026,
    tour: 'both',
    category: 'slam',
    surface: 'clay',
    surface_label: 'Saibro · outdoor',
    location: 'Stade Roland Garros, Paris · 🇫🇷',
    country: 'FRA',
    flag: '🇫🇷',
    start_date: '2026-05-24',
    end_date: '2026-06-07',
    prize_money: '€56M',
    draw_size: '128S · 64D',
    status: 'scheduled',
    atp_winner: null, atp_finalist: null, atp_score: null,
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'Próximo Slam. Modelo prevê: Alcaraz 38% · Sinner 24% · Djokovic 9%.',
    wiki_slug: '2026_French_Open',
  },
  {
    slug: 'wimbledon-2026',
    name: 'Wimbledon',
    full_name: 'The Championships, Wimbledon 2026',
    year: 2026,
    tour: 'both',
    category: 'slam',
    surface: 'grass',
    surface_label: 'Grama · outdoor',
    location: 'All England Club, Londres · 🇬🇧',
    country: 'GBR',
    flag: '🍓',
    start_date: '2026-06-29',
    end_date: '2026-07-12',
    prize_money: '£50M',
    draw_size: '128S · 64D',
    status: 'scheduled',
    atp_winner: null, atp_finalist: null, atp_score: null,
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'Slam em grama. Modelo prevê: Alcaraz 31% · Sinner 26%.',
    wiki_slug: '2026_Wimbledon_Championships',
  },
  {
    slug: 'us-open-2026',
    name: 'US Open',
    full_name: 'US Open 2026',
    year: 2026,
    tour: 'both',
    category: 'slam',
    surface: 'hard',
    surface_label: 'Hard · outdoor',
    location: 'USTA Billie Jean King, Nova Iorque · 🇺🇸',
    country: 'USA',
    flag: '🍎',
    start_date: '2026-08-25',
    end_date: '2026-09-07',
    prize_money: '$70M',
    draw_size: '128S · 64D',
    status: 'scheduled',
    atp_winner: null, atp_finalist: null, atp_score: null,
    wta_winner: null, wta_finalist: null, wta_score: null,
    story: 'Slam em hard. Modelo prevê: Sinner 33% · Alcaraz 22%.',
    wiki_slug: '2026_US_Open',
  },
];

(async () => {
  console.log(`Inserindo ${tournaments.length} torneios...`);
  const rows = await Promise.all(
    tournaments.map(async t => ({
      slug: t.slug,
      name: t.name,
      full_name: t.full_name,
      year: t.year,
      tour: t.tour,
      category: t.category,
      surface: t.surface,
      surface_label: t.surface_label,
      location: t.location,
      country: t.country,
      flag: t.flag,
      start_date: t.start_date,
      end_date: t.end_date,
      prize_money: t.prize_money,
      draw_size: t.draw_size,
      status: t.status,
      atp_winner_id: t.atp_winner ? await getPlayerId(t.atp_winner) : null,
      atp_finalist_id: t.atp_finalist ? await getPlayerId(t.atp_finalist) : null,
      atp_score: t.atp_score,
      wta_winner_id: t.wta_winner ? await getPlayerId(t.wta_winner) : null,
      wta_finalist_id: t.wta_finalist ? await getPlayerId(t.wta_finalist) : null,
      wta_score: t.wta_score,
      story: t.story,
      wiki_slug: t.wiki_slug,
    }))
  );

  const { data, error } = await supabase
    .from('tournaments')
    .upsert(rows, { onConflict: 'slug' })
    .select('id, name, status');

  if (error) {
    console.error('❌ Erro:', error);
    process.exit(1);
  }
  console.log(`✓ ${data.length} torneios inseridos:`);
  data.forEach(t => console.log(`  - ${t.name} (${t.status})`));
})();
